### ISSUE TITLE
The travis is failed

### ISSUE THREAD

**Issue by freesky-edward** [huaweicloud/terraform-provider-telefonicaopencloud#1]
The CI system has been integrated, however the status is failed with some reason. I would report an issue to  fix this.

**Comment by niuzhenguo** [comment]
Currently only `make vendor-status` failed as we modified gophercloud locally, which can be addressed after refactoring vendor to use golangsdk.

**Comment by freesky-edward** [comment]
@niuzhenguo all is good now. I think this can be close now

**Comment by niuzhenguo** [comment]
yes, thanks!
