### ISSUE TITLE
Terraform Provider Development Program - Initial Review

### ISSUE THREAD

**Issue by bill-rich** [huaweicloud/terraform-provider-telefonicaopencloud#5]
Hello!

Its Bill @ HashiCorp again!

I’ve taken a look at the provider and (as with FlexibleEngine), it is looking great! I have a few items to track and discuss below. The review was done on the git commit 8dbe0e8.

- [x] There are some sections of code that have been commented out. If they are not needed, it would probably be best to remove them to keep things clean. Here are a few examples:
  - MaxRetries, S3ForcePathStyle, “fmt.Printf("[DEBUG] Region: %s.\n", c.Region) in config.go
  - Block in resource_telefonicaopencloud_elb_loadbalancer.go
- [x] Remove and zuul.yaml.
- [x] CHANGELOG.md needs to be filled in.
- [x] Aws variable naming in config.go seem to be for swift provider, but it may be good to revisit naming to not reference AWS.
- [x] Similar issue with naming referencing AWS in function testAccAWSS3MultiBucketConfigWithTags & TestAccAWSS3MultiBucket_withTags in resource_telefonicaopencloud_s3_bucket_test.go.
- [x] Several grammatical errors:
  -examples/autoscaling-with-alarm/README.md: “status. the scenario” & “End user want a server group”
  -compute_instance_v2_networking.go: “on an telefonicaopencloud...“ -> “on a telefonicaopencloud...“
- [x] Remove comments for test results. e.g. data_source_telefonicaopencloud_rds_flavors_v1_test.go
- [x] Standard libraries should be grouped in imports. Looks to be in several files, such as resource_telefonicaopencloud_as_configuration_v1 & resource_telefonicaopencloud_as_group_v1.
- [ ] Splitting out some of the nested schema in resource_telefonicaopencloud_as_configuration_v1.go could help make the schema more readable and possibly make some portions reusable. This isn't really necessary, but I wanted to bring up the possibility if you feel that it fits. See [here](https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/vsphere/internal/virtualdevice/virtual_machine_cdrom_subresource.go) for an example.
- [x] Indentation formatting can be improved in getAllClusterJobs in resource_telefonicaopencloud_mrs_cluster_v1.go.
- [x] ForceNew is not needed in data sources since the data is refreshed on each planning anyway.

Again, things are looking very good. Thanks for all the hard work!

Bill

**Comment by niuzhenguo** [comment]
@bill-rich Thanks for the review! As with FlexibleEngine provider, we also have a stable/terraform branch here for reviewing which already addressed some issues above and I will try to address the rest soon, then please check out there, thanks in advance!

**Comment by bill-rich** [comment]
Ah, thank you for the info on the stable branch. I'll use that from here on out. I plan to be working on the review for terraform-provider-huaweicloud soon, so I'll make sure to use the stable/terraform branch there also.

I added one additional item about ForceNew in data sources that I had left out originally.

**Comment by niuzhenguo** [comment]
@bill-rich yes, we also have a stable/terraform branch on huaweicloud for your review, please check out there, thanks!

**Comment by niuzhenguo** [comment]
@bill-rich Regarding splitting out the nested schema, thanks for bringing up the possibilities and the example. If it's not a hard request here, I plan to do it later on next release. All the other issues have been addressed, please have a look again, thanks in advance!

**Comment by bill-rich** [comment]
Its not a hard request at all. I'm not even certain it applies to your situation. Just wanted to point out the possibility. 

Thanks for addressing all the issues! I'll take a look at it first thing in the (PDT) morning.

**Comment by niuzhenguo** [comment]
@bill-rich Great, thanks!

**Comment by bill-rich** [comment]
Things are looking really good. I ran goimports and found a couple more files where the import grouping/sorting should be adjusted:
telefonicaopencloud/import_telefonicaopencloud_s3_bucket.go
telefonicaopencloud/resource_telefonicaopencloud_compute_floatingip_v2.go
telefonicaopencloud/resource_telefonicaopencloud_s3_bucket_test.go

I think other than that things are set to go! Great work!

**Comment by niuzhenguo** [comment]
@bill-rich done, please have a look again when you got time, thanks in advance!

**Comment by bill-rich** [comment]
@niuzhenguo Looks great! I think this one is ready now too.

**Comment by niuzhenguo** [comment]
@bill-rich Thanks!

**Comment by niuzhenguo** [comment]
@cgriggs01 Please have a look at this, thanks!
btw, I removed RDS resource support #13 to address its acc test issue due to some server side problems.

**Comment by cgriggs01** [comment]
Hey @niuzhenguo, Great work with the provider we are ready to release it. The last thing to do is get all the acceptance test passing in the TC environment. I've added you to the project already, so you should be able to see why the tests are currently failing.

**Comment by niuzhenguo** [comment]
@cgriggs01 Thanks, will investigate the CI problems soon!

**Comment by niuzhenguo** [comment]
@cgriggs01 hi, I find a problem with the new repo on terraform-providers which is base on git commit a10ad3a instead of the current stable-terraform branch. The commits to address feedbacks from @bill-rich are not included.

**Comment by niuzhenguo** [comment]
@cgriggs01 I have cherry-picked the commits to the new repo. I will close this and follow up with you via email.
